name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Parse_nix:
    runs-on: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f"
      - uses: "cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d"
      - name: "Parse .nix files"
        run: |
          git ls-files | grep '.nix$' | xargs nix-instantiate --parse --quiet > /dev/null
  Instantiation:
    runs-on: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f"
      - uses: "cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Instantiation"
        run: |
          nix-env --out-path -qaP --no-name -f .ci/instantiate-all.nix \
            | sed -e 's/\+\+/./g' \
            | sort
  Documentation:
    runs-on: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f"
      - uses: "cachix/install-nix-action@07da2520eebede906fbeefa9dd0a2b635323909d"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Build documentation"
        run: |
          nix-build doc
          cp -prf $(readlink -f result) built-documentation
      - uses: actions/upload-artifact@v1
        with:
          name: documentation
          path: built-documentation
