# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "ahci" "sd_mod" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/vda1";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  networking.useDHCP = false;
  networking.interfaces.ens3.ipv4.addresses = [
    {
      address = "192.135.112.85";
      prefixLength = 23;
    }
  ];
  networking.defaultGateway.interface = "ens3";
  networking.defaultGateway.address = "192.135.112.1";
  networking.nameservers = [
    "1.1.1.1"
    "1.0.0.1"
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}