matrix:
  SYSTEM:
    - e4mc-eu
    - bridget
    - thorley

steps:
  - name: build
    image: nixpkgs/cachix-flakes
    commands:
      - nix profile install nixpkgs#attic-client
      - cachix use vgskye
      - attic login twm https://attic.is-quite.gay $ATTIC_TOKEN
      - attic use skye
      - nix build .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel
      - attic push skye ./result
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: cachix_token
      ATTIC_TOKEN:
        from_secret: attic_token
    when:
      branch: sanitary
      event: push

labels:
  platform: linux/aarch64
  backend: docker