matrix:
  SYSTEM:
    - e4mc-eu
    - thorley

steps:
  - name: build
    image: nixpkgs/cachix-flakes
    commands:
      - nix profile install nixpkgs#attic-client
      - nix profile install .#nix-fast-build
      - export PATH=$PATH:~/.nix-profile/bin
      - attic login fly https://skyettic.fly.dev $ATTIC_TOKEN
      - attic use fly-skye
      - nix-fast-build --eval-workers 1 --attic-cache fly-skye --skip-cached --no-nom --flake .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: cachix_token
      ATTIC_TOKEN:
        from_secret: attic_token
    when:
      branch: sanitary
      event: push

labels:
  platform: linux/arm64
  backend: docker