matrix:
  SYSTEM:
    - e4mc-eu
    - thorley

steps:
  - name: build
    image: nixpkgs/cachix-flakes
    commands:
      - nix profile install nixpkgs#attic-client
      - nix profile install nixpkgs#nix-fast-build
      - export PATH=$PATH:~/.nix-profile/bin
      - attic login twm https://new-attic.is-quite.gay $ATTIC_TOKEN
      - attic use skye
      - nix-fast-build --attic-cache skye --no-nom --flake .#nixosConfigurations.${SYSTEM}.config.system.build.toplevel
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: cachix_token
      ATTIC_TOKEN:
        from_secret: attic_token
    when:
      branch: sanitary
      event: push

labels:
  platform: linux/arm64
  backend: docker