steps:
  - name: build
    image: nixpkgs/cachix-flakes
    commands:
      - nix profile install nixpkgs#attic-client
      - nix profile install .#nix-fast-build
      - export PATH=$PATH:~/.nix-profile/bin
      - attic login fly https://attic.is-quite.gay $ATTIC_TOKEN
      - attic use fly-skye
      - nix-fast-build --eval-workers 1 --attic-cache fly-skye --skip-cached --no-nom --flake .#nixosConfigurations.e4mc-jp.config.system.build.toplevel
      - nix-fast-build --eval-workers 1 --attic-cache fly-skye --skip-cached --no-nom --flake .#nixosConfigurations.e4mc-oc.config.system.build.toplevel
      - nix-fast-build --eval-workers 1 --attic-cache fly-skye --skip-cached --no-nom --flake .#nixosConfigurations.e4mc-us.config.system.build.toplevel
      - nix-fast-build --eval-workers 1 --attic-cache fly-skye --skip-cached --no-nom --flake .#nixosConfigurations.e4mc-ap.config.system.build.toplevel
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: cachix_token
      ATTIC_TOKEN:
        from_secret: attic_token
    when:
      branch: sanitary
      event: push

labels:
  platform: linux/amd64
  backend: docker