steps:
  - name: build
    image: nixpkgs/cachix-flakes
    commands:
      - nix profile install nixpkgs#attic-client
      - export PATH=$PATH:~/.nix-profile/bin
      - cachix use vgskye
      - attic login twm https://attic.is-quite.gay $ATTIC_TOKEN
      - attic use skye
      - nix build .#nixosConfigurations.e4mc-jp.config.system.build.toplevel
      - attic push skye ./result
      - nix build .#nixosConfigurations.e4mc-oc.config.system.build.toplevel
      - attic push skye ./result
      - nix build .#nixosConfigurations.e4mc-us.config.system.build.toplevel
      - attic push skye ./result
      - nix build .#nixosConfigurations.e4mc-ap.config.system.build.toplevel
      - attic push skye ./result
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: cachix_token
      ATTIC_TOKEN:
        from_secret: attic_token
    when:
      branch: sanitary
      event: push

labels:
  platform: linux/amd64
  backend: docker