steps:
  - name: build
    image: nixpkgs/cachix-flakes
    commands:
      - nix profile install nixpkgs#attic-client
      - nix profile install github:Mic92/nix-fast-build
      - export PATH=$PATH:~/.nix-profile/bin
      - attic login twm https://new-attic.is-quite.gay $ATTIC_TOKEN
      - attic use skye
      - nix-fast-build --eval-workers 2 --attic-cache skye --skip-cached --no-nom --flake .#homeConfigurations.bs2k-arm.activationPackage
    environment:
      CACHIX_AUTH_TOKEN:
        from_secret: cachix_token
      ATTIC_TOKEN:
        from_secret: attic_token
    when:
      branch: sanitary
      event: push

labels:
  platform: linux/arm64
  backend: docker